<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\klip.ico</ApplicationIcon>
    <RootNamespace>Klip</RootNamespace>
    <AssemblyName>Klip</AssemblyName>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <InformationalVersion>1.0.0</InformationalVersion>
    <Product>Клип</Product>
    <AssemblyTitle>Клип</AssemblyTitle>
    <Company>scarrymany</Company>
    <Authors>scarrymany</Authors>
    <Copyright>© 2026 scarrymany</Copyright>
    <Description>Менеджер буфера обмена для Windows 10 и 11</Description>
    <NeutralLanguage>ru</NeutralLanguage>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <DebugType>embedded</DebugType>
    <SatelliteResourceLanguages>ru;en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Using Remove="System.Drawing" />
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\klip.ico" />
  </ItemGroup>

</Project>
