name: Идея
description: Предложение по Клипу
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: Что добавить
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Зачем это нужно
